# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# Documentation: https://goreleaser.com
version: 2

project_name: mewbot-go

before:
  hooks:
    - go mod tidy

builds:
  - id: mewbot
    main: ./cmd/mewbot
    binary: mewbot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/mewisme/mewbot-go/cmd/mewbot.version={{.Version}}
      - -X github.com/mewisme/mewbot-go/cmd/mewbot.commit={{.Commit}}
      - -X github.com/mewisme/mewbot-go/cmd/mewbot.date={{.Date}}

archives:
  - id: mewbot
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

release:
  draft: false
  prerelease: auto
